name: Android Build

on:
  push:
    branches: [ "main", "patch-1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository Manually
      run: |
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin ${{ github.ref_name }}
        git checkout ${{ github.ref_name }}

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: ignore
